(() => {
  "use strict";
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const STORE = "mojRasporyadok.v2";
  const todayISO = (d=new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
  const uid = () => Math.random().toString(36).slice(2,10) + Date.now().toString(36);
  const safe = (s="") => String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const categories = {study:"Учёба",work:"Работа",sport:"Спорт",rest:"Отдых",other:"Другое"};
  const defaultTemplates = [
    {id:"tpl-study",name:"Учебный день",symbol:"📚",description:"Сбалансированный день для занятий и отдыха.",tasks:[["08:00","08:30","Завтрак","rest"],["09:00","11:00","Учёба: главный предмет","study"],["11:15","12:00","Повторение материала","study"],["13:00","14:00","Домашние задания","study"],["17:00","18:00","Прогулка или тренировка","sport"]]},
    {id:"tpl-weekend",name:"Выходной",symbol:"☀️",description:"Неспешный день с отдыхом и личными делами.",tasks:[["09:00","10:00","Спокойное утро","rest"],["11:00","12:00","Личные дела","other"],["13:00","14:00","Прогулка","sport"],["16:00","17:00","Хобби","rest"]]},
    {id:"tpl-focus",name:"День концентрации",symbol:"🎯",description:"Рабочие блоки с перерывами для восстановления.",tasks:[["09:00","10:30","Главная задача","work"],["10:30","10:45","Перерыв","rest"],["10:45","12:15","Второй блок работы","work"],["14:00","15:00","Завершить важные дела","work"]]},
    {id:"tpl-exam",name:"Подготовка к экзамену",symbol:"✍️",description:"Повторение, практика и разбор ошибок.",tasks:[["09:00","10:00","Повторить теорию","study"],["10:15","11:15","Решить задания","study"],["12:00","12:45","Разобрать ошибки","study"],["16:00","16:30","Короткое повторение","study"]]}
  ];
  let data = load();
  let selectedDate = todayISO();
  let toastTimer;
  function fresh(){return {tasks:[],notes:[],templates:[],habits:[],goals:[],matrix:{do:[],schedule:[],delegate:[],eliminate:[]},completedByDate:{},theme:"light"}}
  function load(){try{const x=JSON.parse(localStorage.getItem(STORE));return x&&typeof x==="object"?{...fresh(),...x}:fresh()}catch{return fresh()}}
  function save(){localStorage.setItem(STORE,JSON.stringify(data))}
  function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2500)}
  function parseDate(s){const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
  function dateText(s,opts={weekday:"long",day:"numeric",month:"long"}){return new Intl.DateTimeFormat("ru-RU",opts).format(parseDate(s))}
  function timeToMin(t){const [h,m]=t.split(":").map(Number);return h*60+m}
  function taskOccurs(t,day){if(t.date===day)return true;if(t.date>day)return false;const dow=parseDate(day).getDay();if(t.repeat==="daily")return true;if(t.repeat==="weekdays")return dow!==0&&dow!==6;if(t.repeat==="weekly")return parseDate(t.date).getDay()===dow;return false}
  function taskKey(t,day){return t.id+"@"+day}
  function isDone(t,day){return !!data.completedByDate[taskKey(t,day)]}
  function setDone(t,day,val){if(val)data.completedByDate[taskKey(t,day)]=true;else delete data.completedByDate[taskKey(t,day)];save();renderAll()}
  function tasksFor(day=selectedDate){return data.tasks.filter(t=>taskOccurs(t,day)).sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title))}
  function categoryPill(c){return `<span class="category-pill ${safe(c)}">${safe(categories[c]||"Другое")}</span>`}
  function openDialog(id){const d=$("#"+id);if(d.showModal)d.showModal();else d.setAttribute("open","")}
  function closeDialog(id){const d=$("#"+id);if(d.close)d.close();else d.removeAttribute("open")}
  function goView(view){$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+view));$$("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));window.scrollTo({top:0,behavior:"smooth"});if(view==="stats")renderStats()}
  function updateDate(){const d=parseDate(selectedDate);$("#topDate").textContent=dateText(todayISO(),{day:"numeric",month:"long",year:"numeric"});$("#dateLabel").textContent=dateText(selectedDate,{weekday:"long",day:"numeric",month:"long"});$("#datePicker").value=selectedDate;$("#dateLabel").title=d.toLocaleDateString("ru-RU")}
  function renderTasks(){
    const all=tasksFor();const query=$("#taskSearch").value.trim().toLowerCase();const cat=$("#categoryFilter").value;
    const filtered=all.filter(t=>(cat==="all"||t.category===cat)&&(!query||(t.title+" "+(t.description||"")).toLowerCase().includes(query)));
    $("#taskList").innerHTML=filtered.map(t=>{const done=isDone(t,selectedDate);return `<article class="task-card ${done?"done":""}" data-task="${safe(t.id)}"><button class="task-check" data-action="toggle" title="${done?"Отметить невыполненным":"Отметить выполненным"}">${done?"✓":""}</button><div class="task-time">${safe(t.start)} – ${safe(t.end)}</div><div class="task-main"><h3 class="task-title">${safe(t.title)}</h3>${t.description?`<p class="task-description">${safe(t.description)}</p>`:""}<div class="task-tags">${categoryPill(t.category)}${t.priority==="high"?'<span class="priority-pill">Высокий приоритет</span>':""}${t.repeat&&t.repeat!=="none"?'<span class="priority-pill">↻ Повторяется</span>':""}</div></div><div class="task-actions"><button class="mini-button" data-action="edit" title="Изменить">✎</button><button class="mini-button" data-action="delete" title="Удалить">⋯</button></div></article>`}).join("");
    $("#taskList").classList.toggle("hidden",filtered.length===0);$("#emptyTasks").classList.toggle("hidden",all.length>0);
    $("#taskSummary").textContent=`${all.length} ${plural(all.length,"дело","дела","дел")} на выбранный день`;
    const done=all.filter(t=>isDone(t,selectedDate)).length;const pct=all.length?Math.round(done/all.length*100):0;
    $("#doneCount").textContent=done;$("#totalCount").textContent=all.length;$("#progressPercent").textContent=pct+"%";$("#progressBar").style.width=pct+"%";$("#progressRing").style.setProperty("--progress",pct+"%");$("#progressHint").textContent=all.length?(pct===100?"Отлично! Все дела выполнены.":"Продолжай в своём темпе — ты справляешься."):"Добавь дела, чтобы увидеть прогресс.";
  }
  function plural(n,a,b,c){n=Math.abs(n)%100;const n1=n%10;return n>10&&n<20?c:n1>1&&n1<5?b:n1===1?a:c}
  function renderClock(){const now=new Date();$("#currentClock").textContent=now.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});const nowMin=now.getHours()*60+now.getMinutes();const upcoming=tasksFor(todayISO()).filter(t=>!isDone(t,todayISO())&&timeToMin(t.end)>nowMin).sort((a,b)=>a.start.localeCompare(b.start))[0];if(!upcoming){$("#nextTaskTitle").textContent="На сегодня пока ничего нет";$("#nextTaskMeta").textContent="Добавь дело, чтобы начать планирование";$("#countdownText").textContent="Нет ближайших дел";return}$("#nextTaskTitle").textContent=upcoming.title;$("#nextTaskMeta").textContent=`${upcoming.start}–${upcoming.end} · ${categories[upcoming.category]||"Другое"}`;const diff=timeToMin(upcoming.start)-nowMin;if(diff<=0)$("#countdownText").textContent=`Уже идёт · до конца ${Math.max(0,timeToMin(upcoming.end)-nowMin)} мин.`;else{const h=Math.floor(diff/60),m=diff%60;$("#countdownText").textContent=`До начала ${h?`${h} ч `:""}${m} мин.`}}
  function openTask(id=null,from=null){const t=id?data.tasks.find(x=>x.id===id):null;$("#taskForm").reset();$("#taskId").value=t?t.id:"";$("#taskDialogTitle").textContent=t?"Изменить дело":"Новое дело";$("#taskTitle").value=t?.title||"";$("#taskStart").value=t?.start||"09:00";$("#taskEnd").value=t?.end||"10:00";$("#taskCategory").value=t?.category||"study";$("#taskPriority").value=t?.priority||"normal";$("#taskDescription").value=t?.description||"";$("#taskRepeat").value=t?.repeat||"none";$("#taskReminder").value=String(t?.reminder||0);$("#deleteTaskBtn").classList.toggle("hidden",!t);openDialog("taskDialog")}
  $("#taskForm").addEventListener("submit",e=>{e.preventDefault();const id=$("#taskId").value;const start=$("#taskStart").value,end=$("#taskEnd").value;if(timeToMin(end)<=timeToMin(start)){toast("Время окончания должно быть позже начала");return}const obj={id:id||uid(),title:$("#taskTitle").value.trim(),start,end,category:$("#taskCategory").value,priority:$("#taskPriority").value,description:$("#taskDescription").value.trim(),repeat:$("#taskRepeat").value,reminder:Number($("#taskReminder").value),date:id?(data.tasks.find(t=>t.id===id)?.date||selectedDate):selectedDate};if(id){data.tasks=data.tasks.map(t=>t.id===id?obj:t)}else data.tasks.push(obj);save();closeDialog("taskDialog");renderAll();toast(id?"Дело обновлено":"Дело добавлено")});
  $("#deleteTaskBtn").addEventListener("click",()=>{const id=$("#taskId").value;if(!id)return;if(confirm("Удалить это дело?")){data.tasks=data.tasks.filter(t=>t.id!==id);Object.keys(data.completedByDate).forEach(k=>{if(k.startsWith(id+"@"))delete data.completedByDate[k]});save();closeDialog("taskDialog");renderAll();toast("Дело удалено")}});
  $("#taskList").addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const card=b.closest("[data-task]");const t=data.tasks.find(x=>x.id===card.dataset.task);if(!t)return;if(b.dataset.action==="toggle")setDone(t,selectedDate,!isDone(t,selectedDate));if(b.dataset.action==="edit")openTask(t.id);if(b.dataset.action==="delete"){if(confirm(`Удалить «${t.title}»?`)){data.tasks=data.tasks.filter(x=>x.id!==t.id);save();renderAll();toast("Дело удалено")}}});
  function applyTemplate(t){const date=selectedDate;const newTasks=t.tasks.map(x=>({id:uid(),date,start:x.start,end:x.end,title:x.title,category:x.category||"other",priority:"normal",description:"",repeat:"none",reminder:0}));if(!newTasks.length){toast("В шаблоне нет дел");return}if(!confirm(`Добавить ${newTasks.length} ${plural(newTasks.length,"дело","дела","дел")} из шаблона «${t.name}» на ${dateText(date,{day:"numeric",month:"long"})}?`))return;data.tasks.push(...newTasks);save();renderAll();goView("schedule");toast("Шаблон применён")}
  function renderTemplates(){const make=t=>`<article class="template-card"><div class="template-symbol">${safe(t.symbol||"▤")}</div><h3>${safe(t.name)}</h3><p>${safe(t.description||"Сохранённый набор дел.")}</p><div class="template-footer"><small>${t.tasks.length} ${plural(t.tasks.length,"дело","дела","дел")}</small><button class="primary-button" data-apply="${safe(t.id)}">Применить →</button></div>${t.custom?`<div class="template-footer"><button class="text-button" data-delete-template="${safe(t.id)}">Удалить шаблон</button></div>`:""}</article>`;$("#templateGrid").innerHTML=defaultTemplates.map(make).join("");$("#customTemplateGrid").innerHTML=data.templates.map(make).join("")||'<p class="muted small">Пока нет собственных шаблонов. Сохрани выбранный день, чтобы он появился здесь.</p>'}
  $("#templateGrid").addEventListener("click",e=>{const b=e.target.closest("[data-apply]");if(b){const t=defaultTemplates.find(x=>x.id===b.dataset.apply);if(t)applyTemplate(t)}});$("#customTemplateGrid").addEventListener("click",e=>{const b=e.target.closest("[data-apply],[data-delete-template]");if(!b)return;if(b.dataset.apply){const t=data.templates.find(x=>x.id===b.dataset.apply);if(t)applyTemplate(t)}else if(confirm("Удалить этот шаблон?")){data.templates=data.templates.filter(x=>x.id!==b.dataset.deleteTemplate);save();renderTemplates()}});
  $("#saveTemplateBtn").addEventListener("click",()=>{if(!tasksFor().length){toast("На выбранном дне нет дел для шаблона");return}$("#templateName").value="";openDialog("templateDialog")});
  $("#templateForm").addEventListener("submit",e=>{e.preventDefault();const ts=tasksFor().filter(t=>!isDone(t,selectedDate)).map(t=>({start:t.start,end:t.end,title:t.title,category:t.category}));data.templates.push({id:uid(),name:$("#templateName").value.trim(),symbol:"✦",description:"Мой сохранённый распорядок",tasks:ts,custom:true});save();closeDialog("templateDialog");renderTemplates();toast("Шаблон сохранён")});
  function openTextDialog(kind,id=null){const item=id?(kind==="note"?data.notes:data.goals).find(x=>x.id===id):null;$("#textForm").dataset.kind=kind;$("#textEntityId").value=id||"";$("#textDialogEyebrow").textContent=kind==="note"?"ЗАМЕТКА":"ЦЕЛЬ";$("#textDialogTitle").textContent=item?(kind==="note"?"Изменить заметку":"Изменить цель"):(kind==="note"?"Новая заметка":"Новая цель");$("#textTitleLabel").firstChild.textContent=kind==="note"?"Название":"Название цели";$("#textBodyLabel").classList.toggle("hidden",kind!=="note");$("#textTitle").value=item?.title||"";$("#textBody").value=item?.body||"";$("#deleteTextBtn").classList.toggle("hidden",!item);openDialog("textDialog")}
  $("#textForm").addEventListener("submit",e=>{e.preventDefault();const kind=e.currentTarget.dataset.kind,id=$("#textEntityId").value,arr=kind==="note"?data.notes:data.goals;const obj=kind==="note"?{id:id||uid(),title:$("#textTitle").value.trim(),body:$("#textBody").value.trim(),updated:new Date().toISOString()}:{id:id||uid(),name:$("#textTitle").value.trim(),target:1,progress:0,unit:""};if(id){const i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]={...arr[i],...obj}}else arr.unshift(obj);save();closeDialog("textDialog");renderAll();toast(kind==="note"?"Заметка сохранена":"Цель обновлена")});
  $("#deleteTextBtn").addEventListener("click",()=>{const kind=$("#textForm").dataset.kind,id=$("#textEntityId").value;if(!id)return;if(confirm("Удалить запись?")){if(kind==="note")data.notes=data.notes.filter(x=>x.id!==id);else data.goals=data.goals.filter(x=>x.id!==id);save();closeDialog("textDialog");renderAll();toast("Удалено")}});
  function renderNotes(){const q=$("#noteSearch").value.trim().toLowerCase();const notes=data.notes.filter(n=>(n.title+" "+n.body).toLowerCase().includes(q));$("#notesGrid").innerHTML=notes.map(n=>`<article class="note-card" data-note="${safe(n.id)}"><div class="note-symbol">▧</div><h3>${safe(n.title)}</h3><p class="note-body">${safe(n.body)}</p><footer><span>${n.updated?new Date(n.updated).toLocaleDateString("ru-RU"):"Заметка"}</span><button class="mini-button" data-edit-note="${safe(n.id)}" aria-label="Редактировать">✎</button></footer></article>`).join("");$("#emptyNotes").classList.toggle("hidden",notes.length>0)}
  $("#addNoteBtn").addEventListener("click",()=>openTextDialog("note"));$("#notesGrid").addEventListener("click",e=>{const b=e.target.closest("[data-edit-note]");if(b)openTextDialog("note",b.dataset.editNote)});$("#noteSearch").addEventListener("input",renderNotes);
  $$(".matrix-form").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const input=$("input",form),val=input.value.trim();if(!val)return;const key=form.dataset.quadrant;data.matrix[key].push({id:uid(),text:val});input.value="";save();renderMatrix()}));
  function renderMatrix(){["do","schedule","delegate","eliminate"].forEach(key=>{$("#matrix-"+key).innerHTML=(data.matrix[key]||[]).map(x=>`<li><span>${safe(x.text)}</span><button data-matrix-delete="${safe(x.id)}" data-quadrant="${key}" aria-label="Удалить">×</button></li>`).join("")})}
  $("#view-matrix").addEventListener("click",e=>{const b=e.target.closest("[data-matrix-delete]");if(!b)return;const k=b.dataset.quadrant;data.matrix[k]=data.matrix[k].filter(x=>x.id!==b.dataset.matrixDelete);save();renderMatrix()});
  function openHabitDialog(){ $("#habitForm").reset();openDialog("habitDialog")}
  $("#addHabitBtn").addEventListener("click",openHabitDialog);$("#emptyHabitBtn").addEventListener("click",openHabitDialog);
  $("#habitForm").addEventListener("submit",e=>{e.preventDefault();data.habits.push({id:uid(),name:$("#habitName").value.trim(),reason:$("#habitReason").value.trim(),start:todayISO(),history:[]});save();closeDialog("habitDialog");renderHabits();toast("Привычка добавлена")});
  function daysBetween(a,b){return Math.max(0,Math.floor((parseDate(b)-parseDate(a))/86400000))}
  function habitDays(h){return daysBetween(h.start,todayISO())}
  function renderHabits(){$("#habitsGrid").innerHTML=data.habits.map(h=>{const days=habitDays(h),record=Math.max(days,...(h.history||[]).map(x=>x.days||0));return `<article class="habit-card"><h3>${safe(h.name)}</h3><p>${safe(h.reason||"Шаг за шагом — каждый день имеет значение.")}</p><div class="habit-count">${days}</div><div class="habit-count-label">${plural(days,"день без привычки","дня без привычки","дней без привычки")}</div><div class="habit-metrics"><div class="habit-metric"><small>Личный рекорд</small><strong>${record} дн.</strong></div><div class="habit-metric"><small>Сбросов</small><strong>${(h.history||[]).length}</strong></div></div><div class="habit-actions"><button class="soft-button danger-button" data-reset-habit="${safe(h.id)}">↻ Сбросить</button><button class="soft-button" data-delete-habit="${safe(h.id)}" title="Удалить привычку">Удалить</button></div></article>`}).join("");$("#emptyHabits").classList.toggle("hidden",data.habits.length>0)}
  $("#habitsGrid").addEventListener("click",e=>{const b=e.target.closest("[data-reset-habit],[data-delete-habit]");if(!b)return;const h=data.habits.find(x=>x.id===(b.dataset.resetHabit||b.dataset.deleteHabit));if(!h)return;if(b.dataset.resetHabit){if(!confirm(`Сбросить счётчик «${h.name}»? Текущая серия сохранится в истории.`))return;h.history=h.history||[];h.history.push({date:todayISO(),days:habitDays(h)});h.start=todayISO();save();renderHabits();toast("Счётчик сброшен. Новый отсчёт начался")}else if(confirm(`Удалить привычку «${h.name}»?`)){data.habits=data.habits.filter(x=>x.id!==h.id);save();renderHabits();toast("Привычка удалена")}});
  $("#addGoalBtn").addEventListener("click",()=>{ $("#goalForm").reset();openDialog("goalDialog")});
  $("#goalForm").addEventListener("submit",e=>{e.preventDefault();data.goals.push({id:uid(),name:$("#goalName").value.trim(),target:Number($("#goalTarget").value),progress:0,unit:$("#goalUnit").value.trim(),deadline:$("#goalDeadline").value});save();closeDialog("goalDialog");renderGoals();toast("Цель создана")});
  function renderGoals(){$("#goalsGrid").innerHTML=data.goals.map(g=>{const pct=Math.min(100,Math.round((g.progress/g.target)*100));return `<article class="goal-card"><h3>${safe(g.name)}</h3><p>${g.deadline?`Срок: ${safe(g.deadline)}`:"Личная цель"}</p><div><strong>${g.progress}</strong> <span class="muted small">из ${g.target} ${safe(g.unit||"шагов")}</span></div><div class="goal-progress"><span style="width:${pct}%"></span></div><div class="muted small">${pct}% выполнено</div><div class="goal-controls"><button data-goal-minus="${safe(g.id)}">−</button><button data-goal-plus="${safe(g.id)}">＋ Добавить прогресс</button><button class="mini-button" data-goal-delete="${safe(g.id)}" title="Удалить">×</button></div></article>`}).join("");$("#emptyGoals").classList.toggle("hidden",data.goals.length>0)}
  $("#goalsGrid").addEventListener("click",e=>{const b=e.target.closest("[data-goal-plus],[data-goal-minus],[data-goal-delete]");if(!b)return;const id=b.dataset.goalPlus||b.dataset.goalMinus||b.dataset.goalDelete;const g=data.goals.find(x=>x.id===id);if(!g)return;if(b.dataset.goalDelete){if(!confirm("Удалить цель?"))return;data.goals=data.goals.filter(x=>x.id!==id)}else if(b.dataset.goalPlus)g.progress=Math.min(g.target,g.progress+1);else g.progress=Math.max(0,g.progress-1);save();renderGoals();renderStats()});
  function renderStats(){const all=data.tasks;const done=Object.keys(data.completedByDate).length;$("#statDone").textContent=done;$("#statTotal").textContent=all.length;$("#statGoals").textContent=data.goals.filter(g=>g.progress<g.target).length;const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const iso=todayISO(d),ts=tasksFor(iso),n=ts.filter(t=>isDone(t,iso)).length;days.push({label:new Intl.DateTimeFormat("ru-RU",{weekday:"short"}).format(d).replace(".",""),n,total:ts.length})}const max=Math.max(1,...days.map(x=>x.total));$("#weeklyStats").innerHTML=days.map(x=>`<div class="bar-day"><span class="bar-value">${x.n}/${x.total}</span><div class="bar-rail"><span style="height:${x.total?Math.max(4,x.n/max*100):3}%"></span></div><span class="bar-label">${safe(x.label)}</span></div>`).join("")}
  function renderAll(){updateDate();renderTasks();renderTemplates();renderNotes();renderMatrix();renderHabits();renderGoals();renderStats();renderClock()}
  $$("[data-view]").forEach(b=>b.addEventListener("click",()=>{
    goView(b.dataset.view);
    if(b.closest(".mobile-nav")) b.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"});
  }));
  $("#addTaskBtn").addEventListener("click",()=>openTask());$("#emptyAddBtn").addEventListener("click",()=>openTask());$("#browseTemplatesBtn").addEventListener("click",()=>goView("templates"));
  $("#prevDay").addEventListener("click",()=>{const d=parseDate(selectedDate);d.setDate(d.getDate()-1);selectedDate=todayISO(d);renderAll()});$("#nextDay").addEventListener("click",()=>{const d=parseDate(selectedDate);d.setDate(d.getDate()+1);selectedDate=todayISO(d);renderAll()});$("#todayBtn").addEventListener("click",()=>{selectedDate=todayISO();renderAll()});$("#datePicker").addEventListener("change",e=>{if(e.target.value){selectedDate=e.target.value;renderAll()}});
  $("#taskSearch").addEventListener("input",renderTasks);$("#categoryFilter").addEventListener("change",renderTasks);
  function toggleTheme(){
    data.theme=data.theme==="dark"?"light":"dark";
    document.body.classList.toggle("dark",data.theme==="dark");
    const mobileTheme=$("#mobileThemeToggle");
    if(mobileTheme){
      mobileTheme.querySelector("span").textContent=data.theme==="dark"?"☀":"☾";
      mobileTheme.querySelector("small").textContent=data.theme==="dark"?"Светлая":"Тема";
      mobileTheme.setAttribute("aria-label",data.theme==="dark"?"Включить светлую тему":"Включить тёмную тему");
    }
    save();
  }
  $("#themeToggle").addEventListener("click",toggleTheme);
  $("#mobileThemeToggle").addEventListener("click",toggleTheme);
  $("#exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="moj-rasporyadok-backup.json";a.click();URL.revokeObjectURL(url);toast("Резервная копия скачана")});
  $("#importInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported||typeof imported!=="object"||!Array.isArray(imported.tasks))throw new Error();if(!confirm("Импорт заменит текущие данные. Продолжить?"))return;data={...fresh(),...imported};save();document.body.classList.toggle("dark",data.theme==="dark");renderAll();toast("Данные импортированы")}catch{toast("Не удалось прочитать файл резервной копии")}finally{e.target.value=""}});
  $$("[data-close]").forEach(b=>b.addEventListener("click",()=>closeDialog(b.dataset.close)));
  $$("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)closeDialog(d.id)}));
  document.body.classList.toggle("dark",data.theme==="dark");
  if($("#mobileThemeToggle")){
    $("#mobileThemeToggle span").textContent=data.theme==="dark"?"☀":"☾";
    $("#mobileThemeToggle small").textContent=data.theme==="dark"?"Светлая":"Тема";
    $("#mobileThemeToggle").setAttribute("aria-label",data.theme==="dark"?"Включить светлую тему":"Включить тёмную тему");
  }
  // Simple daily reminders, only after the user explicitly grants permission.
  async function requestNotifications(){if(!("Notification"in window)){toast("Уведомления не поддерживаются браузером");return}const p=await Notification.requestPermission();toast(p==="granted"?"Уведомления разрешены":"Разрешение на уведомления не получено")}
  renderAll();setInterval(renderClock,15000);
  // Expose a small opt-in entry point without interrupting the user on page load.
  window.enablePlannerNotifications=requestNotifications;
})();